### ISSUE TITLE
Repo template as baseline

### ISSUE THREAD

**Issue by inigomarquinez** [onebeyond/maintainers#1]
Things to be included in the template:

- [x] Code of conduct
- [ ] Contribution guidelines
- [x] Codeowners
- [x] Do the settings apply to the new repositories based on the template? (e.g. branch protection rules)

**Comment by UlisesGascon** [comment]
I add few more things:
- #15
- #16

**Comment by inigomarquinez** [comment]
[This](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types) is the list of supported file types that we can add at the organization level.

**Comment by inigomarquinez** [comment]
Example repo template: https://github.com/oracle/template-repo

**Comment by inigomarquinez** [comment]
Almost everything is included using community health files, and we don’t have anything more to add right now to the template. So we’ll close the issue and we’ll open new ones if we want to include more things to the template.
