### ISSUE TITLE
Continous Integration tooling

### ISSUE THREAD

**Issue by UlisesGascon** [onebeyond/maintainers#10]
In the past we used several solutions to run the the build, tests, deployments in Npm... I will suggest to use Github Actions and migrate the legacy ones (if needed). What do you think @onebeyond/maintainers

**Comment by inigomarquinez** [comment]
@UlisesGascon , as discussed we all agreed that it would be a great idea to migrate and start using GitHub actions in all the OB repos. Should we close this issue? Perhaps we should open a new one to review which repos need to be fixed / migrated to GitHub actions.

**Comment by UlisesGascon** [comment]
Yep, we can close this issue and create a new one with the repos that require migration or addition 👍
