### ISSUE TITLE
Repos with NPM version mismatch

### ISSUE THREAD

**Issue by UlisesGascon** [onebeyond/maintainers#29]
Here I am mapping out all the NPM packages that have some kind of version mismatch between repo releases, pkg versions and NPM available version. This was produced by manual releases in the past:
- [x] [systemic-rabbitmq](https://github.com/onebeyond/systemic-rabbitmq). Missing release 1.0.1. [Solved](https://github.com/onebeyond/systemic-rabbitmq/releases/tag/1.0.1)
- [x] [confabulous-http-loader](https://github.com/onebeyond/confabulous-http-loader) pkg is in v0.1.0 and NPM in v0.1.1 (lead by @carpasse )
- [ ] [systemic-azure-metrics](https://github.com/onebeyond/systemic-azure-metrics) v0.3.0 not yet released in NPM ( waiting for #28 )
- [ ] [systemic-pg](https://github.com/onebeyond/systemic-pg) Missing release 3.0.0 in repo (Lead by @inigomarquinez )

**Comment by carpasse** [comment]
I would like to try to help with this. I will try to reach @UlisesGascon next week

**Comment by UlisesGascon** [comment]
Thank u @carpasse !! Let's have a look next week :)

**Comment by inigomarquinez** [comment]
I would also like to contribute @UlisesGascon !
