### ISSUE TITLE
Create a secrets management repository

### ISSUE THREAD

**Issue by UlisesGascon** [onebeyond/maintainers#30]
We need a little private repository to share credentials to 3rd parties and bots for the @onebeyond/admins.

I will create a repository using Blackbox and provide a good documentation about it

**Comment by UlisesGascon** [comment]
@onebeyond/maintainers the repo is ready, let me know if you feel confortable with it so I can start pushing the secrets :)

**Comment by inigomarquinez** [comment]
Closing this issue as the repo has already been created and works as expected.
