### ISSUE TITLE
Provide autoinvitation link to slack

### ISSUE THREAD

**Issue by UlisesGascon** [onebeyond/maintainers#40]
The objetive will be to include invitation links in the readme files, so potential contributors can join the slack easily.

**Comment by UlisesGascon** [comment]
@CesarD I will ping you when is ready ;)

**Comment by inigomarquinez** [comment]
@UlisesGascon , should we include this link in the repo template we created for new projects? https://github.com/onebeyond/open-source-project-template

The only problem I see is that the link expires after 7 days. Do you know a way to have a permanent link?

**Comment by UlisesGascon** [comment]
This was solved already
