### ISSUE TITLE
Scheduled reminders

### ISSUE THREAD

**Issue by inigomarquinez** [onebeyond/maintainers#59]
GitHub offers the possibility to connect to a slack workspace to set Scheduled reminders.

https://github.com/organizations/onebeyond/settings/reminders

Do we want to enable them in the organization and connect to our slack org?

**Comment by UlisesGascon** [comment]
I added the app to the channel `#05-notifications` in slack

<img width="1059" alt="Captura de pantalla 2023-06-24 a las 12 11 15" src="https://github.com/onebeyond/maintainers/assets/5110813/a6ba6690-d185-4dd4-b1a9-08ebcb690989">

I created a basic reminder:
![Captura de pantalla 2023-06-24 a las 12 10 08](https://github.com/onebeyond/maintainers/assets/5110813/ea3ed0df-0b88-4be5-aac9-735540f068f4)


Full details:
![screencapture-github-organizations-onebeyond-settings-reminders-60490-2023-06-24-12_10_26](https://github.com/onebeyond/maintainers/assets/5110813/495cb9ef-0ad3-4f5f-841b-909e7f0f5b69)


So... any PR with `reminder` label will trigger a Slack Message

**Comment by inigomarquinez** [comment]
Nice!
