### ISSUE TITLE
Define migration strategy and start the process

### ISSUE THREAD

**Issue by UlisesGascon** [onebeyond/maintainers#6]
There is already a clear list, we just need to organize the priorities and preestablish the teams (see: #5)

**Comment by UlisesGascon** [comment]
First 25 repositories already migrated in Nov 🎉

**Comment by UlisesGascon** [comment]
All the repos in scope for Guidesmiths are already migrated 🎉

**Comment by inigomarquinez** [comment]
@UlisesGascon , should be close this issue as it has already been solved?

**Comment by UlisesGascon** [comment]
yeah! this can be closed :-)
