### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by inigomarquinez** [onebeyond/maintainers#60]
Do we want to force the users in the organization to have 2FA enabled?

https://github.com/organizations/onebeyond/settings/security

**Comment by inigomarquinez** [comment]
Already enabled

![Captura de pantalla 2023-03-23 a las 16 04 05](https://user-images.githubusercontent.com/25435858/227246266-a23e6b9a-7405-473f-91a0-a397abb93efe.png)

**Comment by UlisesGascon** [comment]
Thanks @inigomarquinez!
